CREATE TABLE events (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id    VARCHAR(64) NOT NULL,
    source      VARCHAR(16) NOT NULL,
    service     VARCHAR(64) NOT NULL,
    severity    VARCHAR(16) NOT NULL,
    message     TEXT        NOT NULL,
    status      VARCHAR(16) NOT NULL,
    timestamp   TIMESTAMPTZ NOT NULL,
    received_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    version     BIGINT      NOT NULL DEFAULT 0,
    CONSTRAINT uk_events_event_id UNIQUE (event_id),
    CONSTRAINT ck_events_source CHECK (source IN ('ATS', 'CBTC', 'SCADA', 'TMS', 'PIS')),
    CONSTRAINT ck_events_severity CHECK (severity IN ('INFO', 'WARNING', 'MAJOR', 'CRITICAL')),
    CONSTRAINT ck_events_status CHECK (status IN ('OPEN', 'ACKNOWLEDGED', 'RESOLVED'))
);

CREATE INDEX idx_events_severity ON events (severity);
CREATE INDEX idx_events_status ON events (status);
CREATE INDEX idx_events_source ON events (source);
CREATE INDEX idx_events_service ON events (service);
CREATE INDEX idx_events_timestamp ON events (timestamp);
